title: Satya's Scratchpad
description: Thoughts on AI, leadership, and the world as I see it
theme: minima

show_excerpts: true

# These help links and SEO (optional but nice)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://tartakoff.github.io"
baseurl: ""   # keep empty for user site
